CREATE TABLE flights_realtime_raw (
    snapshot_ts TIMESTAMP NOT NULL DEFAULT NOW(),
    hex VARCHAR(20),
    reg_number VARCHAR(20),
    flag VARCHAR(5),
    lat NUMERIC(10, 6),
    lng NUMERIC(10,6),
    alt INTEGER,
    dir NUMERIC(7, 2),
    speed INTEGER,
    v_speed INTEGER,
    flight_number VARCHAR(10),
    flight_icao VARCHAR(10),
    flight_iata VARCHAR(10),
    dep_icao VARCHAR(10),
    dep_iata VARCHAR(10),
    arr_icao VARCHAR(10),
    arr_iata VARCHAR(10),
    airline_icao VARCHAR(10),
    airline_iata VARCHAR(10),
    aircraft_icao VARCHAR(10),
    updated BIGINT,
    status VARCHAR(50),
    type VARCHAR(50),
    squawk VARCHAR(10)
);

CREATE TABLE flights_realtime_clean (
    id SERIAL PRIMARY KEY,
    snapshot_ts TIMESTAMP NOT NULL DEFAULT NOW(),
    hex VARCHAR(20),
    reg_number VARCHAR(20),
    flag VARCHAR(5),
    latitude NUMERIC(10, 6),
    longitude NUMERIC(10,6),
    altitude_ft INTEGER,
    dir NUMERIC(7, 2),
    speed_mph INTEGER,
    v_speed_mph INTEGER,
    flight_number VARCHAR(10),
    flight_icao VARCHAR(10),
    flight_iata VARCHAR(10),
    departure_icao VARCHAR(10),
    departure_iata VARCHAR(10),
    arrival_icao VARCHAR(10),
    arrival_iata VARCHAR(10),
    airline_icao VARCHAR(10),
    airline_iata VARCHAR(10),
    aircraft_icao VARCHAR(10),
    updated TIMESTAMP,
    status VARCHAR(50),
    type VARCHAR(50),
    squawk VARCHAR(10)
);